import type { GetContentsDataType } from '../types'

export function getServerValidatorContents({ nuxt, options }: GetContentsDataType): string {
  const formats = options?.validator?.formats

  return `// ! Generated by nuxt-feathers - do not change manually
// For more information about this file see https://dove.feathersjs.com/guides/cli/validators.html

import type { FormatsPluginOptions } from '@feathersjs/schema'
import { addFormats, Ajv } from '@feathersjs/schema'

const formats: FormatsPluginOptions = [
  '${formats?.join(`',\n  '`)}'
]

export const dataValidator: Ajv = addFormats(new Ajv({}), formats)

export const queryValidator: Ajv = addFormats(
  new Ajv({
    coerceTypes: true,
  }),
  formats,
)
`
}
