import type { ClientOptions } from '../../options'
import type { GetContentsDataType } from '../types'
import { put } from '../utils'

export function getClientContents({ options }: GetContentsDataType): string {
  const pinia = !!(options?.client as ClientOptions)?.pinia

  const apiType = pinia ? 'FeathersPiniaClient<ClientApplication>' : 'ClientApplication'

  return `// ! Generated by nuxt-feathers - do not change manually
import type { Application, TransportConnection } from '@feathersjs/feathers'
${put(pinia, `import type { FeathersPiniaClient } from 'feathers-pinia'`)}

export interface Configuration {
  connection: TransportConnection<ServiceTypes>
}

export interface ServiceTypes {}

export type ClientApplication = Application<ServiceTypes, Configuration>

export type FeathersClientPlugin = Parameters<ClientApplication['configure']>['0']

export function defineFeathersClientPlugin(def: FeathersClientPlugin): FeathersClientPlugin {
  return def;
}

declare module '#app' {
  interface NuxtApp {
    $api: ${apiType}
  }
}

declare module 'vue' {
  interface ComponentCustomProperties {
    $api: ${apiType}
  }
}
`
}
