import type { GetContentsDataType } from '../types'

export function getClientContents({ options }: GetContentsDataType): string {
  return `// ! Generated by nuxt-feathers - do not change manually
import type { Application, TransportConnection } from '@feathersjs/feathers'

export interface Configuration {
  connection: TransportConnection<ServiceTypes>
}

export interface ServiceTypes {}

export type ClientApplication = Application<ServiceTypes, Configuration>

export type FeathersClientPlugin = Parameters<ClientApplication['configure']>['0']

export function defineFeathersClientPlugin(def: FeathersClientPlugin): FeathersClientPlugin {
  return def;
}
`
}
