import type { ClientOptions, DefaultAuthOptions } from '../../options'
import type { ServicesDirs } from '../../options/services'
import type { GetContentsDataType } from '../types'
import { type Import, scanDirExports } from 'unimport'
import { put } from '../utils'

export async function getClientPluginContents({ options }: GetContentsDataType): Promise<string> {
  const services = (await scanDirExports(options.servicesDirs as ServicesDirs, {
    filePatterns: ['**/*.shared.ts'],
    fileFilter: file => /shared.ts$/.test(file),
    types: false,
  })).filter(({ name }) => /Client|default$/.test(name))

  const plugins = (options.client as ClientOptions).plugins as Array<Import>

  const modules = [...services, ...plugins]

  const auth = ((options?.auth as DefaultAuthOptions)?.authStrategies || []).length > 0

  return `// ! Generated by nuxt-feathers - do not change manually
// For more information about this file see https://dove.feathersjs.com/guides/cli/client.html

import type { ClientApplication } from './client'
import { feathers } from '@feathersjs/feathers'
import { defineNuxtPlugin } from '#app'
import { createPiniaClient } from 'feathers-pinia'

${put(auth, `import { authentication } from './authentication'`)}
import { connection } from './connection'

${modules.map(module => `import ${module.name === 'default' ? module.as : `{ ${module.as} }`} from '${module.from.replace('.ts', '')}'`).join('\n')}

/**
 * Returns a typed client for the feathers-api app.
 *
 * @param connection The REST or Socket.io Feathers client connection
 * @param authenticationOptions Additional settings for the authentication client
 * @see https://dove.feathersjs.com/api/client.html
 * @returns The Feathers client application
 */
function createClient(): ClientApplication {
  const feathersClient: ClientApplication = feathers()

  // Init connection
  feathersClient.configure(connection)

  // Init authentication
  ${put(auth, `feathersClient.configure(authentication)`)}

  // Init services
  ${services.map(service => `feathersClient.configure(${service.as})`).join('\n  ')}

  // Init plugins
  ${plugins.map(plugin => `feathersClient.configure(${plugin.as})`).join('\n  ')}

  return feathersClient
}

/**
 * Creates a Feathers Rest client for the SSR server and a Socket.io client for the browser.
 * Also provides a cookie-storage adapter for JWT SSR using Nuxt APIs.
 */
export default defineNuxtPlugin(async (nuxt) => {
  // create the feathers client
  const feathersClient: ClientApplication = createClient()

  // wrap the feathers client
  const api = createPiniaClient(feathersClient, {
    pinia: nuxt.$pinia,
    ssr: !!import.meta.server,
    idField: 'id', // use _id for mongoDB
    whitelist: [],
    paramsForServer: [],
    skipGetIfExists: true,
    customSiftOperators: {},
  })

  return { provide: { api } }
})
`
}
